"""Added partner_1 and partner_2 to reservation table.

Revision ID: 2e5881ea0f56
Revises: 693c6f0ec910
Create Date: 2024-06-13 00:23:27.776378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5881ea0f56'
down_revision = '693c6f0ec910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('partner_2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('partner_2')
        batch_op.drop_column('partner_1')

    # ### end Alembic commands ###
