"""Change avater user id to unique.

Revision ID: 4731b72bc856
Revises: bc8860673714
Create Date: 2024-06-12 12:45:53.234636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4731b72bc856'
down_revision = 'bc8860673714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_avatar_user_id', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_constraint('uq_avatar_user_id', type_='unique')
    # ### end Alembic commands ###
