"""Added event and image model.

Revision ID: e1a924bd3fa8
Revises: 4f206bee5759
Create Date: 2024-06-06 15:02:46.668773

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e1a924bd3fa8'
down_revision = '4f206bee5759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('image_id', sa.String(length=255), nullable=True),
                    sa.Column('starts_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.Column('image', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('event_id')
                    )
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_avatar_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar', schema=None) as batch_op:
        batch_op.drop_constraint('uq_avatar_user_id', type_='unique')

    op.drop_table('image')
    op.drop_table('event')
    # ### end Alembic commands ###
